// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpVIpyagu1riD6aZLKciDC2v29bFc8jSs',
    appId: '1:19488598058:web:6106d8fbdc5aa378adbb53',
    messagingSenderId: '19488598058',
    projectId: 'productivityapp-5f122',
    authDomain: 'productivityapp-5f122.firebaseapp.com',
    storageBucket: 'productivityapp-5f122.firebasestorage.app',
    measurementId: 'G-YE2GWGB9SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMIdAc36sYOM7kQJFKAfJTogTNP5wYIYY',
    appId: '1:19488598058:android:d3cfc72d191228ebadbb53',
    messagingSenderId: '19488598058',
    projectId: 'productivityapp-5f122',
    storageBucket: 'productivityapp-5f122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2mWgaBmLJDX8SjsNW_q8FR05zUs7IXvQ',
    appId: '1:19488598058:ios:3b15232d83e5b5cdadbb53',
    messagingSenderId: '19488598058',
    projectId: 'productivityapp-5f122',
    storageBucket: 'productivityapp-5f122.firebasestorage.app',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2mWgaBmLJDX8SjsNW_q8FR05zUs7IXvQ',
    appId: '1:19488598058:ios:3b15232d83e5b5cdadbb53',
    messagingSenderId: '19488598058',
    projectId: 'productivityapp-5f122',
    storageBucket: 'productivityapp-5f122.firebasestorage.app',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpVIpyagu1riD6aZLKciDC2v29bFc8jSs',
    appId: '1:19488598058:web:4805ab4dfe083670adbb53',
    messagingSenderId: '19488598058',
    projectId: 'productivityapp-5f122',
    authDomain: 'productivityapp-5f122.firebaseapp.com',
    storageBucket: 'productivityapp-5f122.firebasestorage.app',
    measurementId: 'G-P8J86VJLT0',
  );
}
